"""initial schema - all 22 entities

Revision ID: 3857d22c304f
Revises: 
Create Date: 2026-03-13 14:28:07.707471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3857d22c304f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('global_role', sa.Enum('admin', 'user', name='global_role_enum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notify_settings', sa.JSON(), nullable=True),
    sa.Column('auto_save_interval_s', sa.Integer(), nullable=False),
    sa.Column('approval_state', sa.Enum('approved', 'pending', 'rejected', name='approval_state_enum'), nullable=False),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lora_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('hf_repo_id', sa.String(length=255), nullable=True),
    sa.Column('civitai_id', sa.String(length=100), nullable=True),
    sa.Column('trigger_words', sa.JSON(), nullable=False),
    sa.Column('nsfw_flag', sa.Boolean(), nullable=False),
    sa.Column('weight_default', sa.Float(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('added_by', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('model_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('image', 'video', 'audio', name='model_type_enum'), nullable=False),
    sa.Column('architecture', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('vram_floor_mb', sa.Integer(), nullable=False),
    sa.Column('vram_recommended_mb', sa.Integer(), nullable=False),
    sa.Column('supports_cpu_offload', sa.Boolean(), nullable=False),
    sa.Column('supports_fp8', sa.Boolean(), nullable=False),
    sa.Column('supports_fp16', sa.Boolean(), nullable=False),
    sa.Column('min_compute_capability', sa.String(length=10), nullable=True),
    sa.Column('param_schema', sa.JSON(), nullable=False),
    sa.Column('compatible_lora_architectures', sa.JSON(), nullable=False),
    sa.Column('lora_weight_min', sa.Float(), nullable=False),
    sa.Column('lora_weight_max', sa.Float(), nullable=False),
    sa.Column('max_lora_stack_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('hf_repo_id', sa.String(length=255), nullable=True),
    sa.Column('civitai_id', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('added_by', sa.String(length=36), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('oauth_identities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('provider', sa.Enum('google', 'discord', name='oauth_provider_enum'), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('provider_email', sa.String(length=255), nullable=False),
    sa.Column('access_token', sa.String(length=1024), nullable=True),
    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.Enum('draft', 'creative_active', 'pending_handoff', 'eng_active', 'pending_return', 'completed', name='project_state_enum'), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('global_negative_prompt', sa.Text(), nullable=True),
    sa.Column('auto_save_interval_s', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('resolution_w', sa.Integer(), nullable=False),
    sa.Column('resolution_h', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('value_type', sa.Enum('string', 'int', 'float', 'bool', 'json', name='setting_value_type_enum'), nullable=False),
    sa.Column('scope', sa.Enum('global', 'user', name='setting_scope_enum'), nullable=False),
    sa.Column('scope_id', sa.String(length=36), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_invites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('batches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('job_count', sa.Integer(), nullable=False),
    sa.Column('done_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'partial_failure', 'failed', name='batch_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('handoff_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('creative_to_eng', 'eng_to_creative', name='handoff_direction_enum'), nullable=False),
    sa.Column('initiated_by', sa.String(length=36), nullable=False),
    sa.Column('accepted_by', sa.String(length=36), nullable=True),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['accepted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['initiated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('handoff_request', 'handoff_accepted', 'handoff_declined', 'return_request', 'return_accepted', 'return_declined', 'job_complete', 'job_failed', 'batch_complete', 'render_complete', 'system_error', name='notification_type_enum'), nullable=False),
    sa.Column('channel', sa.Enum('in_app', 'email', 'webhook', name='notification_channel_enum'), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('creative', 'engineer', 'viewer', name='project_role_enum'), nullable=False),
    sa.Column('assigned_by', sa.String(length=36), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('lora_stack', sa.JSON(), nullable=False),
    sa.Column('scope', sa.Enum('global', 'project', name='template_scope_enum'), nullable=False),
    sa.Column('scope_project_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('auto_time', 'auto_event', 'manual', 'checkpoint', name='snapshot_type_enum'), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('storyboards',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('timelines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('fps', sa.Integer(), nullable=False),
    sa.Column('resolution_w', sa.Integer(), nullable=False),
    sa.Column('resolution_h', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id')
    )
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('image_generation', 'video_generation', 'audio_generation', 'interpolation', 'inpaint', 'outpaint', 'render', 'export', name='job_type_enum'), nullable=False),
    sa.Column('source_entity_type', sa.Enum('keyframe', 'videoclip', 'audioclip', 'project', name='source_entity_type_enum'), nullable=False),
    sa.Column('source_entity_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='job_status_enum'), nullable=False),
    sa.Column('priority', sa.Enum('high', 'medium', 'normal', 'low', name='job_priority_enum'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=True),
    sa.Column('gpu_target', sa.Enum('local', 'vastai', name='gpu_target_enum'), nullable=False),
    sa.Column('vastai_instance_id', sa.String(length=255), nullable=True),
    sa.Column('vram_estimate_mb', sa.Integer(), nullable=True),
    sa.Column('vram_actual_mb', sa.Integer(), nullable=True),
    sa.Column('cost_estimate_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('cost_actual_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('user_ack', sa.Boolean(), nullable=False),
    sa.Column('user_ack_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ack_by', sa.String(length=36), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=True),
    sa.Column('eta_seconds', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=100), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('log_stream_id', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ack_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tracks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timeline_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('video', 'audio', 'controlnet', name='track_type_enum'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('muted', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['timeline_id'], ['timelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('type', sa.Enum('image', 'video', 'audio', name='asset_type_enum'), nullable=False),
    sa.Column('subtype', sa.Enum('still', 'i2i', 'inpaint', 'outpaint', 'controlnet_frame', 'clip', 'interpolated', 'v2v', 'music', 'sfx', 'tts', 'lipsync', 'export', name='asset_subtype_enum'), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('lora_stack', sa.JSON(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('render_state', sa.Enum('unrendered', 'rendering', 'done', 'error', name='render_state_enum'), nullable=False),
    sa.Column('subtype', sa.Enum('music', 'sfx', 'tts', 'lipsync', name='audio_subtype_enum'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('model_source', sa.Enum('local', 'api', name='model_source_enum'), nullable=False),
    sa.Column('api_provider', sa.String(length=100), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('fade_in_ms', sa.Integer(), nullable=False),
    sa.Column('fade_out_ms', sa.Integer(), nullable=False),
    sa.Column('pan', sa.Float(), nullable=False),
    sa.Column('loop', sa.Boolean(), nullable=False),
    sa.Column('sync_to_asset_id', sa.String(length=36), nullable=True),
    sa.Column('sync_mode', sa.Enum('free', 'locked', name='sync_mode_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['sync_to_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyframes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('storyboard_id', sa.String(length=36), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('neg_prompt_scope', sa.Enum('keyframe', 'global', name='neg_prompt_scope_enum'), nullable=False),
    sa.Column('mode', sa.Enum('t2i', 'i2i', 'inpaint', 'outpaint', name='keyframe_mode_enum'), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('seed_mode', sa.Enum('fixed', 'random', 'variation', name='seed_mode_enum'), nullable=False),
    sa.Column('variation_count', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('lora_stack', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cn_enabled', sa.Boolean(), nullable=False),
    sa.Column('cn_type', sa.Enum('depth', 'canny', 'pose', 'reference', name='cn_type_enum'), nullable=True),
    sa.Column('cn_control_asset_id', sa.String(length=36), nullable=True),
    sa.Column('cn_strength', sa.Float(), nullable=True),
    sa.Column('cn_start_pct', sa.Float(), nullable=True),
    sa.Column('cn_end_pct', sa.Float(), nullable=True),
    sa.Column('selected_asset_id', sa.String(length=36), nullable=True),
    sa.Column('candidate_asset_ids', sa.JSON(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cn_control_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['selected_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['storyboard_id'], ['storyboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_clips',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('track_id', sa.String(length=36), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('source_asset_id', sa.String(length=36), nullable=True),
    sa.Column('output_asset_id', sa.String(length=36), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.Column('render_state', sa.Enum('unrendered', 'rendering', 'done', 'error', name='render_state_enum'), nullable=False),
    sa.Column('mode', sa.Enum('t2v', 'i2v', 'v2v', name='video_mode_enum'), nullable=False),
    sa.Column('model_id', sa.String(length=36), nullable=True),
    sa.Column('lora_stack', sa.JSON(), nullable=False),
    sa.Column('positive_prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('frames', sa.Integer(), nullable=True),
    sa.Column('fps', sa.Integer(), nullable=True),
    sa.Column('motion_strength', sa.Float(), nullable=True),
    sa.Column('steps', sa.Integer(), nullable=True),
    sa.Column('cfg_scale', sa.Float(), nullable=True),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('cn_enabled', sa.Boolean(), nullable=False),
    sa.Column('cn_type', sa.Enum('depth', 'canny', 'pose', 'reference', name='cn_type_enum'), nullable=True),
    sa.Column('cn_control_asset_id', sa.String(length=36), nullable=True),
    sa.Column('cn_strength', sa.Float(), nullable=True),
    sa.Column('cn_start_pct', sa.Float(), nullable=True),
    sa.Column('cn_end_pct', sa.Float(), nullable=True),
    sa.Column('rife_enabled', sa.Boolean(), nullable=False),
    sa.Column('rife_multiplier', sa.Enum('2x', '4x', name='rife_multiplier_enum'), nullable=False),
    sa.Column('scene_cut_detect', sa.Boolean(), nullable=False),
    sa.Column('interp_blend_mode', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cn_control_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.ForeignKeyConstraint(['output_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['source_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_clips')
    op.drop_table('keyframes')
    op.drop_table('audio_clips')
    op.drop_table('prompt_history')
    op.drop_table('assets')
    op.drop_table('tracks')
    op.drop_table('jobs')
    op.drop_table('timelines')
    op.drop_table('storyboards')
    op.drop_table('snapshots')
    op.drop_table('prompt_templates')
    op.drop_table('project_members')
    op.drop_table('notifications')
    op.drop_table('handoff_records')
    op.drop_table('batches')
    op.drop_table('user_invites')
    op.drop_table('settings')
    op.drop_table('projects')
    op.drop_table('oauth_identities')
    op.drop_table('model_registry')
    op.drop_table('lora_registry')
    op.drop_table('users')
    # ### end Alembic commands ###
